version: "3.5"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=auctions
    networks:
      - auction
    volumes:
      - mongodb:/data/db
  auction:
    container_name: auction
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: auction:latest
    ports:
      - "8081:8081"
    environment:
      DATABASESERVER_PORT: "27017"
    depends_on:
      - mongodb
    networks:
      - auction
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart:
      unless-stopped
networks:
  auction:
    name: network_name
volumes:
  mongodb:
    driver: local
